[package]
name = "lockchain-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
lockchain-core = { path = "../lockchain-core" }
lockchain-zfs = { path = "../lockchain-zfs" }
dbus = "0.9"
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread","macros"] }
