#!/usr/bin/env bash
printf "\033[36m                _________\n"
printf "             .-'  _   _  '-.\n"
printf "           .'    ( ) ( )    '.\n"
printf "          /    .-----------.  \\\n\033[0m"
printf "\033[35m   ==o==\033[0m\033[36m       /  .-------.  \\       \033[0m\033[35m==o==\n\033[0m"
printf "\033[35m  [____]\033[0m\033[36m      |  |  _____  |  |      \033[0m\033[35m[____]\n\033[0m"
printf "\033[36m              |  | |  _  | |  |\n"
printf "              |  | | (_) | |  |\n"
printf "              |  | |_____| |  |\n"
printf "              |  |    |    |  |\n"
printf "              |  |   _|_   |  |\n"
printf "              |  |  /___\\  |  |\n"
printf "               \\  '-------'  /\n"
printf "                '._       _.'\n"
printf "                   '-._.-'\n\n"
printf "                 LOCKCHAIN\n"
printf "                ZFS EDITION\033[0m\n"
