name: Bug report
description: Something isn't working
labels: ["type:bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: A clear and concise description...
    validations: { required: true }
  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: e.g. v0.1.0 or abc1234
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: ["S1 - blocker", "S2 - major", "S3 - minor"]
    validations: { required: true }
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1) ... 2) ... 3) ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
