blank_issues_enabled: false
contact_links:
  - name: Security disclosure
    url: https://github.com/OWNER/REPO/security/advisories/new
    about: Please report vulnerabilities privately via GitHub Advisories.
