[package]
name = "lockchain-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
serde_yaml = "0.9"
thiserror = "1"
log = "0.4"
hex = "0.4"
pbkdf2 = "0.12"
sha2 = "0.10"
zeroize = "1"

[dev-dependencies]
tempfile = "3"
