[package.metadata.deb]
maintainer = "Lock Chain Team dev@lockchain.io
"
depends = "zfsutils-linux, systemd"
assets = [
["target/release/lockchain-cli", "usr/bin/", "755"],
["target/release/lockchain-daemon", "usr/bin/", "755"],
["target/release/lockchain-ui", "usr/bin/", "755"],
["packaging/systemd/", "lib/systemd/system/", "644"],
["packaging/udev/", "lib/udev/rules.d/", "644"],
["packaging/dracut/*", "usr/lib/dracut/modules.d/90lockchain/", "755"]
]
maintainer-scripts = {
postinst = "packaging/debian/postinst",
prerm = "packaging/debian/prerm"
}
